server:
  port: 8888
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  profiles:
    active: dev

jwt:
  signerKey: "eckHkXTVgJ4afjvluzL4chCPtVqs2MtTNLoTQTE6KYjdk8J9QbeQ7V81r6iTUhjp"
  valid-duration: 3600 # in second
  refreshable-duration: 360000 # in second