spring:
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans
          - metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  signerKey: "eckHkXTVgJ4afjvluzL4chCPtVqs2MtTNLoTQTE6KYjdk8J9QbeQ7V81r6iTUhjp"
  valid-duration: 20 # in second
  refreshable-duration: 360000 # in second
