server:
  port: 8888
spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  profiles:
    active: dev
